/**
 * Bundle src/web.src.mjs -> web.mjs as a single self-contained ESM module.
 *
 * The host serves web.mjs raw and the browser dynamically import()s it, so it
 * must resolve with zero bare imports. We inline @wterm/dom + socket.io-client
 * and keep React EXTERNAL (the host injects it via props.React), matching how
 * pi-crust loads external web activities.
 */
import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

await build({
  entryPoints: [path.join(root, 'src', 'web.src.mjs')],
  outfile: path.join(root, 'web.mjs'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  legalComments: 'none',
  // wterm ships a REQUIRED stylesheet (.wterm/.term-grid/.term-row: monospace
  // font, dark bg, cell layout). It is not imported by wterm's JS and the host
  // serves web.mjs raw with no CSS pipeline, so we inline the CSS as a string
  // (text loader) and inject it as a <style> tag at runtime. Without this the
  // terminal renders as unstyled proportional text on the page background.
  loader: { '.css': 'text' },
  // React is provided by the host via props.React; never bundle it.
  external: ['react', 'react-dom'],
  banner: { js: '/* @cemoody/pi-crust-ext-terminal web module — generated by scripts/build-web.mjs. Do not edit. */' },
});

console.log('built web.mjs');
